/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mySidebar: [
    // 'rules',
    // 'resources',
    {
      type: 'category',
      label: 'Snippets',
      items: [
        {
          type: 'category',
          label: 'React',
          items: [
            {
              type: 'autogenerated',
              dirName: 'snippets/react',
            },
          ],
        },
        {
          type: 'category',
          label: 'Redux',
          items: [
            {
              type: 'autogenerated',
              dirName: 'snippets/redux',
            },
          ],
        },
        {
          type: 'category',
          label: 'Javascript',
          items: [
            {
              type: 'autogenerated',
              dirName: 'snippets/javascript',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Linux',
      items: [
        {
          type: 'autogenerated',
          dirName: 'linux',
        },
      ],
    },
    {
      type: 'category',
      label: 'Notes',
      items: [
        {
          type: 'autogenerated',
          dirName: 'notes',
        },
      ],
    },
    {
      type: 'category',
      label: 'Design',
      items: [
        {
          type: 'autogenerated',
          dirName: 'design',
        },
      ],
    },
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
